export const languages = [
  {key:0, value: 'coffee', name: 'Coffee Script'},
  {key:1, value: 'csharp', name: 'C#'},
  {key:2, value: 'css', name: 'CSS'},
  {key:3, value: 'c_cpp', name: 'C++'},
  {key:4, value: 'elixir', name: 'Elixir'},
  {key:5, value: 'golang', name: 'Golang'},
  {key:6, value: 'handlebars', name: 'Handlebars'},
  {key:7, value: 'haskell', name: 'Haskell'},
  {key:8, value: 'html', name: 'HTML'},
  {key:9, value: 'lua', name: 'Lua'},
  {key:10, value: 'java', name: 'Java'},
  {key:11, value: 'json', name: 'JSON'},
  {key:12, value: 'javascript', name: 'JavaScript'},
  {key:13, value: 'markdown', name: 'Markdown'},
  {key:14, value: 'matlab', name: 'Matlab'},
  {key:15, value: 'mysql', name: 'MySQL'},
  {key:16, value: 'objectivec', name: 'Objective-C'},
  {key:17, value: 'php', name: 'PHP'},
  {key:18, value: 'python', name: 'Python'},
  {key:19, value: 'r', name: 'R'},
  {key:20, value: 'ruby', name: 'Ruby'},
  {key:21, value: 'rust', name: 'Rust'},
  {key:22, value: 'sass', name: 'Sass'},
  {key:23, value: 'scala', name: 'Scala'},
  {key:24, value: 'typescript', name: 'Typescript'},
  {key:25, value: 'xml', name: 'XML'},
  {key:26, value: 'plain_text', name: 'plain text'}
];
